### ISSUE TITLE
There is no .xpr project file in this repository

### ISSUE THREAD

**Issue by cnicho35** [Digilent/Arty-A7-35-GPIO#3]
Seems like there is supposed to be one in the proj folder

**Comment by artvvb** [comment]
When cloned, the XPR is created using the python script in digilent-vivado-scripts, as documented in [this subsection](https://github.com/digilent/digilent-vivado-scripts/tree/ffa3f4f7bea46dc30645e1b618701ea3806b7707#3-making-changes-to-a-project-that-uses-this-submodule) of the submodule's README. The XPR can be obtained by downloading the [2018.2-1 release](https://github.com/Digilent/Arty-A7-35-GPIO/releases/tag/v2018.2-1)'s exported project ZIP archive.

**Comment by eliotstock** [comment]
Step 4 of that subsection fails on Ubuntu 20.04:

```
$python3 ./digilent-vivado-scripts/git_vivado.py checkout
Traceback (most recent call last):
  File "./digilent-vivado-scripts/git_vivado.py", line 106, in <module>
    config_settings = config[operating_system]
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Linux'
```

**Comment by eliotstock** [comment]
Opened this for the above error:

https://github.com/Digilent/digilent-vivado-scripts/issues/17
